- type: entity
  save: false
  parent: BaseMobSpecies
  id: CMBaseMobSpeciesOrganic
  abstract: true
  name: Urist C.M. McHands
  suffix: RMC14
  components:
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.35
        density: 185
        restitution: 0.0
        mask:
        - MobMask
        - BarbedBarricade
        layer:
        - Opaque
        - XenoProjectileImpassable
      fix2:
        shape:
          !type:PhysShapeCircle
          radius: 0.25
        density: 185
        restitution: 0.0
        layer:
        - BulletImpassable
  - type: SolutionContainerManager
  - type: InjectableSolution
    solution: chemicals
  - type: Bloodstream
    bloodReagent: Blood
    bloodMaxVolume: 560
    maxBleedAmount: 50
    bleedReductionAmount: 0
    bloodRefreshAmount: 0.15
    bloodlossDamage:
      types:
        Bloodloss: 0.5
    bloodlossHealDamage:
      types:
        Bloodloss: -1
    damageBleedModifiers: CMBloodlossHuman
  - type: Woundable
  - type: StatusEffects
    allowed:
    - Stun
    - KnockedDown
    - PainKnockOut
    - SlowedDown
    - Stutter
    - SeeingRainbows
    - Electrocution
    - ForcedSleep
    - TemporaryBlindness
    - Drunk
    - SlurredSpeech
    - RatvarianLanguage
    - PressureImmunity
    - Muted
    - Pacified
    - StaminaModifier
    - Flashed
    - Dazed
  - type: Blindable
  - type: Tag
    tags:
    - CanPilot
    - FootstepSound
    - DoorBumpOpener
  - type: Marine
  - type: RMCSuitLight
  - type: HolocardState
  - type: Hunger
    baseDecayRate: 0.025
    thresholds:
      Overfed: 550
      Okay: 400
      Peckish: 250
      Starving: 50
      Dead: 0
    hungerThresholdDecayModifiers:
      Overfed: 1
      Okay: 1
      Peckish: 1
      Starving: 1
      Dead: 0
  - type: Thirst
    baseDecayRate: 0.01666666666
  - type: SlowOnDamage # nullify from BaseMobSpecies
    speedModifierThresholds:
      0: 1
  - type: Pain # TODO change to normal from testing
    painLevels:
    - !type:TryChangePainLevelTo
      level: 0
      conditions:
      - !type:PainPercentage
        min: 0
        max: 20
    - !type:TryChangePainLevelTo
      level: 1
      conditions:
      - !type:PainPercentage
        min: 20
        max: 30
    - !type:TryChangePainLevelTo
      level: 2
      conditions:
      - !type:PainPercentage
        min: 30
        max: 40
    - !type:TryChangePainLevelTo
      level: 3
      conditions:
      - !type:PainPercentage
        min: 40
        max: 60
    - !type:TryChangePainLevelTo
      level: 4
      conditions:
      - !type:PainPercentage
        min: 60
        max: 75
    - !type:TryChangePainLevelTo
      level: 5
      conditions:
      - !type:PainPercentage
        min: 75
        max: 85
    - !type:TryChangePainLevelTo
      level: 6
      conditions:
      - !type:PainPercentage
        min: 85
    - !type:MovespeedModifier
      walkSpeedModifier: 0.79
      sprintSpeedModifier: 0.67
      conditions:
      - !type:PainLevel
        level: 1
    - !type:PopupMessage
      type: Local
      messages: [ "rmc-pain-mild-inner" ]
      probability: 0.1
      conditions:
      - !type:PainLevel
        level: 1
    - !type:MovespeedModifier
      walkSpeedModifier: 0.71
      sprintSpeedModifier: 0.67
      conditions:
      - !type:PainLevel
        level: 2
    - !type:PopupMessage
      type: Local
      messages: [ "rmc-pain-discomforting-inner" ]
      probability: 0.1
      conditions:
      - !type:PainLevel
        level: 2
    - !type:MovespeedModifier
      walkSpeedModifier: 0.57
      sprintSpeedModifier: 0.42
      conditions:
      - !type:PainLevel
        level: 3
    - !type:PopupMessage
      type: Local
      messages: [ "rmc-pain-moderate-inner" ]
      probability: 0.1
      conditions:
      - !type:PainLevel
        level: 3
    - !type:MovespeedModifier
      walkSpeedModifier: 0.5
      sprintSpeedModifier: 0.35
      conditions:
      - !type:PainLevel
        level: 4
    - !type:TemporaryBlurryVision
      blur: 3
      time: 4
      conditions:
      - !type:PainLevel
        level: 4
    - !type:GenericStatusEffect
      key: Stutter
      component: StutteringAccent
      time: 4
      conditions:
      - !type:PainLevel
        level: 4
    - !type:PopupMessage
      type: Local
      messages: [ "rmc-pain-distressing-inner" ]
      probability: 0.1
      conditions:
      - !type:PainLevel
        level: 4
    - !type:Emote
      emote: PainGrimace
      showInChat: true
      probability: 0.033
      conditions:
      - !type:PainLevel
        level: 4
    - !type:MovespeedModifier
      walkSpeedModifier: 0.45
      sprintSpeedModifier: 0.31
      conditions:
      - !type:PainLevel
        level: 5
    - !type:TemporaryBlurryVision
        blur: 5
        time: 4
        conditions:
        - !type:PainLevel
          level: 5
    - !type:GenericStatusEffect
        key: Stutter
        component: StutteringAccent
        time: 4
        conditions:
        - !type:PainLevel
          level: 5
    - !type:GenericStatusEffect # substitution of do once in 13
      key: PainKnockOut
      component: PainKnockOut
      probability: 0.01 # this is around 45% chance per minute 1-(1-0.01)^60
      time: 6
      conditions:
      - !type:PainLevel
        level: 5
    - !type:HealthChange
      damage:
        types:
          Asphyxiation: 0.1
      conditions:
      - !type:PainLevel
          level: 5
    - !type:PopupMessage
      type: Local
      messages: [ "rmc-pain-severe-inner" ]
      probability: 0.1
      conditions:
      - !type:PainLevel
        level: 5
    - !type:Emote
      emote: TroubleEyeOpen
      showInChat: true
      probability: 0.033
      conditions:
      - !type:PainLevel
        level: 5
    - !type:MovespeedModifier
      walkSpeedModifier: 0.45
      sprintSpeedModifier: 0.31
      conditions:
      - !type:PainLevel
        level: 6
    - !type:GenericStatusEffect
        key: Stutter
        component: StutteringAccent
        time: 4
        conditions:
        - !type:PainLevel
          level: 6
    - !type:GenericStatusEffect
        key: PainKnockOut
        component: PainKnockOut
        time: 4
        conditions:
        - !type:PainLevel
          level: 6
    - !type:TemporaryBlurryVision
        blur: 5
        time: 4
        conditions:
        - !type:PainLevel
          level: 6
    - !type:HealthChange
      damage:
        types:
          Asphyxiation: 0.5
      conditions:
      - !type:PainLevel
          level: 6
    - !type:PopupMessage
      type: Local
      messages: [ "rmc-pain-horrible-inner" ]
      probability: 0.1
      conditions:
      - !type:PainLevel
        level: 6
    - !type:Emote
      emote: TroubleStanding
      showInChat: true
      probability: 0.033
      conditions:
      - !type:PainLevel
        level: 6
  - type: Body
    prototype: Human
    requiredLegs: 2
  - type: Damageable
    damageContainer: Biological
    damageModifierSet: null
    healthBarThreshold: 5
  - type: Vocal
    sounds:
      Male: MaleHuman
      Female: FemaleHuman
      Unsexed: MaleHuman
  - type: Flammable
    fireSpread: false
    canResistFire: true
    firestackFade: 1
    damage:
      types:
        Heat: 1
  - type: FireVisuals
    sprite: Mobs/Effects/onfire.rsi
    normalState: Generic_mob_burning
    alternateState: Standing
  - type: MeleeWeapon
    soundHit:
      collection: Punch
    angle: 30
    animation: WeaponArcFist
    attackRate: 1
    damage:
      types:
        Blunt: 5
  - type: CMSurgeryTarget
  - type: UserInterface
    interfaces:
      enum.VoiceMaskUIKey.Key:
        type: VoiceMaskBoundUserInterface
      enum.HumanoidMarkingModifierKey.Key:
        type: HumanoidMarkingModifierBoundUserInterface
      enum.StrippingUiKey.Key:
        type: StrippableBoundUserInterface
      enum.CMSurgeryUIKey.Key:
        type: CMSurgeryBui
      enum.HolocardChangeUIKey.Key:
        type: HolocardChangeBoundUserInterface
        interactionRange: 0
      enum.CMMobStateActionsUI.Key:
        type: CMGhostActionBui
        requireInputValidation: false
      enum.TacticalMapUserUi.Key:
        type: TacticalMapUserBui
      enum.SquadLeaderTrackerUI.Key:
        type: SquadInfoBui
      enum.DialogUiKey.Key:
        type: DialogBui
      enum.ViewIntelObjectivesUI.Key:
        type: ViewIntelObjectivesBui
  - type: Infectable
  - type: Tackleable
  - type: Tackle
  - type: XenoNestable
  - type: Devourable
  - type: ImmuneToClothingRequiredStepTrigger
  - type: Undisposable
  - type: ShortExamine
  - type: MaxDamage
    max: 719 # TODO RMC14 this should be per part and smaller
  - type: Perishable
    rotAfter: 300
  - type: AtmosExposed
  - type: Temperature
    heatDamageThreshold: 325
    coldDamageThreshold: 260
    currentTemperature: 310.15
    specificHeat: 42
  - type: TemperatureSpeed
    thresholds:
      273: 1
  - type: ThermalRegulator
    metabolismHeat: 800
    radiatedHeat: 100
    implicitHeatRegulation: 500
    sweatHeatRegulation: 2000
    shiveringHeatRegulation: 2000
    normalBodyTemperature: 310.15
    thermalRegulationTemperatureThreshold: 25
  - type: DamageMobState
    critDamage:
      types:
        Asphyxiation: 1
    nonDeadDamage:
      types:
        Asphyxiation: -0.33
  - type: NoSlip
  - type: NoClothingSlowdown
  - type: RMCSize
    size: Humanoid
  - type: AffectableByWeeds
  - type: UserIFF
  - type: UserLimitHits
  - type: MovementIgnoreGravity
  - type: MovementSpeedModifier
    baseWalkSpeed: 2.7
    baseSprintSpeed: 5
  - type: SlowOnPull
    slowdowns:
    - multiplier: 0.745
      whitelist:
        components:
        - Marine
    - multiplier: 0.855
      whitelist:
        components:
        - XenoLight
    - multiplier: 0.5775
      whitelist:
        components:
        - XenoHeavy
    - multiplier: 0.645
      whitelist:
        tags:
        - BodyBag
  - type: MobThresholds
    thresholds:
      0: Alive
      150: Critical
      200: Dead
  - type: MobStateActions
    actions:
      Critical:
      - CMActionGhost
      Dead:
      - CMActionGhost
  - type: Destructible
    thresholds: [ ]
  - type: NpcFactionMember
    factions:
    - UNMC
  - type: RMCNightVisionVisible
  - type: CrashLandable
  - type: StunShakeable
  - type: StunShakeableUser
  - type: MindCheck
  - type: GenericVisualizer
    visuals:
      enum.CreamPiedVisuals.Creamed:
        clownedon:
          True: { visible: true }
          False: { visible: false }
      enum.UserAcidedVisuals.Acided:
        acided:
          None:
            visible: false
          Normal:
            sprite: _RMC14/Effects/xeno_spray_acid.rsi
            state: human_acid
            visible: true
          Enhanced:
            sprite: _RMC14/Effects/xeno_spray_acid.rsi
            state: human_acid_enhanced
            visible: true
      enum.HookedVisuals.Hooked:
        hooked:
          True: { visible: true }
          False: { visible: false }
  - type: ActiveInputMover
  - type: DropItemsOnRest
  - type: UserBlockShootingInsideContainers
  - type: TacticalMapTracked
    trackDead: true
  - type: TacticalMapUser
    actionId: RMCActionOpenTacticalMapMarine
    marines: true
  - type: EmoteCooldown
  - type: FiremanCarriable
  - type: CanFiremanCarry
  - type: RMCSuicide
    damage:
      types:
        Piercing: 100
        Asphyxiation: 200
  - type: RMCUserPryingRequiresTool
  - type: BlockEntityStorage
    whitelist:
      components:
      - CanBeSupplyDropped
  - type: NewPlayerLabel
  - type: MarineMapTracked
  - type: Evasion
  - type: CanBeFirePatted
  - type: FirePatter
    blacklist:
      components:
      - Xeno
  - type: RMCPickupDroppedItems
  - type: CommendationReceiver
  - type: RMCSpeciesSlowdownModifier
    slowMultiplier: 0.66
    superSlowMultiplier: 0.33
  - type: RMCHandEmotes
  - type: RMCBuckleDrawDepth
